db:
  host: "0.0.0.0"
  port: 3307 # docker map 3307(host) to 3306(docker container)
  user: "root"
  password: "123456" #my own is not this
  dbname: "bubble"
  max_idle_conn: 5
  max_open_conn: 20
  max_idle_time: 300